/**
 * 下書き記事の読み取り・バリデーションユーティリティ
 * content/drafts/*.mdx を扱う。Next.js 非依存。
 */

import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import type { ArticleCategory } from './categories'
import type { MangaPanel, FaqItem, MonetizeItem, ReasonItem, RegionBlock, XSeriesLabel } from './articles'

// =====================================================
// 型
// =====================================================

export type ArticleIdea = {
  title: string
  slug: string
  category: ArticleCategory
  targetKeyword: string
  intent: string
  xSeries?: XSeriesLabel
  monetizeItems?: string[]
}

export type DraftFrontmatter = {
  title: string
  description: string
  category: ArticleCategory
  date: string
  emoji: string
  status: 'draft'
  reviewRequired: true
  autoGenerated: true
  conclusion: string
  reasons: ReasonItem[]
  manga: { panels: MangaPanel[] }
  faqs: FaqItem[]
  relatedSlugs?: string[]
  monetizeItems?: string[]
  region?: RegionBlock
  xSeries?: XSeriesLabel
  mangaPrompt?: string
}

export type Draft = DraftFrontmatter & {
  slug: string
  content: string
}

export type ValidationWarning = {
  field: string
  message: string
}

export type ValidationResult = {
  valid: boolean
  warnings: ValidationWarning[]
}

// =====================================================
// 定数
// =====================================================

export const DRAFTS_DIR = path.join(process.cwd(), 'content', 'drafts')

const PRODUCT_MAP_KEYS = [
  '保冷バッグ', '保冷剤', 'ポータブル電源', 'モバイルバッテリー',
  '非常食', '携帯トイレ', 'ランタン', '懐中電灯', 'カセットコンロ',
  '水', '防災リュック', 'チェックリスト',
]

// =====================================================
// ファイル操作
// =====================================================

export function getAllDraftSlugs(): string[] {
  if (!fs.existsSync(DRAFTS_DIR)) return []
  return fs
    .readdirSync(DRAFTS_DIR)
    .filter((f) => f.endsWith('.mdx'))
    .map((f) => f.replace(/\.mdx$/, ''))
}

export function getDraftBySlug(slug: string): Draft | null {
  const filePath = path.join(DRAFTS_DIR, `${slug}.mdx`)
  if (!fs.existsSync(filePath)) return null
  const raw = fs.readFileSync(filePath, 'utf-8')
  const { data, content } = matter(raw)
  return {
    slug,
    content,
    title: data.title ?? '',
    description: data.description ?? '',
    category: data.category ?? 'disaster-prep',
    date: data.date ?? '',
    emoji: data.emoji ?? '📄',
    status: 'draft',
    reviewRequired: true,
    autoGenerated: true,
    conclusion: data.conclusion ?? '',
    reasons: data.reasons ?? [],
    manga: data.manga ?? { panels: [] },
    faqs: data.faqs ?? [],
    relatedSlugs: data.relatedSlugs,
    monetizeItems: data.monetizeItems,
    region: data.region,
    xSeries: data.xSeries,
    mangaPrompt: data.mangaPrompt,
  }
}

export function getAllDrafts(): Draft[] {
  return getAllDraftSlugs()
    .map(getDraftBySlug)
    .filter((d): d is Draft => d !== null)
    .sort((a, b) => (a.date < b.date ? 1 : -1))
}

// =====================================================
// 品質バリデーション
// =====================================================

export function validateDraftQuality(draft: Draft): ValidationResult {
  const warnings: ValidationWarning[] = []

  if (!draft.conclusion || draft.conclusion.trim().length < 10) {
    warnings.push({ field: 'conclusion', message: 'conclusion が短すぎるか未設定' })
  }

  if (!Array.isArray(draft.reasons) || draft.reasons.length < 3) {
    warnings.push({ field: 'reasons', message: `reasons が ${draft.reasons?.length ?? 0} 件（3件必要）` })
  }

  const panels = draft.manga?.panels ?? []
  if (panels.length !== 4) {
    warnings.push({ field: 'manga.panels', message: `manga.panels が ${panels.length} コマ（4コマ必要）` })
  }

  if (!Array.isArray(draft.faqs) || draft.faqs.length < 3) {
    warnings.push({ field: 'faqs', message: `faqs が ${draft.faqs?.length ?? 0} 件（3件以上必要）` })
  }

  for (const item of draft.monetizeItems ?? []) {
    if (!PRODUCT_MAP_KEYS.includes(item)) {
      warnings.push({ field: 'monetizeItems', message: `"${item}" は PRODUCT_MAP 未登録` })
    }
  }

  const dangerWords = ['絶対に安全', '必ず助かる', '危険はない', '死なない', 'ガスを吸っても']
  for (const w of dangerWords) {
    if (draft.content.includes(w)) {
      warnings.push({ field: 'content', message: `危険表現を含む可能性: "${w}"` })
    }
  }

  const medicalWords = ['治療すれば', '投薬すれば', '手術すれば', '診断は']
  for (const w of medicalWords) {
    if (draft.content.includes(w)) {
      warnings.push({ field: 'content', message: `医療断定表現の可能性: "${w}"` })
    }
  }

  return { valid: warnings.length === 0, warnings }
}
