/**
 * 記事下書き自動生成スクリプト
 *
 * 必須環境変数:
 *   ANTHROPIC_API_KEY — Claude API キー
 *
 * 実行例:
 *   npx tsx scripts/generateArticleDraft.ts
 *   npx tsx scripts/generateArticleDraft.ts --slug blackout-smartphone-battery
 *   npx tsx scripts/generateArticleDraft.ts --force     # 既存下書きを上書き
 *   npx tsx scripts/generateArticleDraft.ts --limit 1   # 未生成のアイデアから1件だけ生成（毎日の自動実行用）
 */

import fs from 'fs'
import path from 'path'
import Anthropic from '@anthropic-ai/sdk'
import matter from 'gray-matter'
import type { ArticleIdea } from '../lib/draftUtils'
import { DRAFTS_DIR, getAllDraftSlugs } from '../lib/draftUtils'
import { getAllSlugs } from '../lib/articles'

// =====================================================
// 定数
// =====================================================

const IDEAS_PATH = path.join(process.cwd(), 'data', 'article-ideas.json')

// =====================================================
// Claude API
// =====================================================

function initClient(): Anthropic {
  const key = process.env.ANTHROPIC_API_KEY
  if (!key) throw new Error('ANTHROPIC_API_KEY が未設定です')
  return new Anthropic({ apiKey: key })
}

// =====================================================
// 既存スラッグ一覧（relatedSlugs 付与用）
// =====================================================

function getSameCategoryRelated(category: string, currentSlug: string): string[] {
  try {
    const all = getAllSlugs()
    const same = all.filter((s) => {
      try {
        const raw = fs.readFileSync(
          path.join(process.cwd(), 'content', 'articles', `${s}.mdx`),
          'utf-8',
        )
        const { data } = matter(raw)
        return data.category === category && s !== currentSlug
      } catch {
        return false
      }
    })
    return same.slice(0, 4)
  } catch {
    return []
  }
}

// =====================================================
// プロンプト
// =====================================================

const SYSTEM_PROMPT = `あなたは防災・防犯専門の記事ライターです。
日本語で、武蔵野市在住の現役医師が監修する防災・防犯情報サイト「防災Lab」向けの記事下書きを生成します。

守るべきルール：
- 誤情報を書かない。不確かな情報は「〜といわれています」「〜が推奨されています」と表現する
- 断定が強すぎる表現（「絶対に安全」「必ず助かる」）は使わない
- 医療情報は一般向け注意喚起に留め、診断・治療の断定はしない
- 危険な行動を推奨しない
- キャラクター名：防災リス（名前：リス）、レスQロボ（名前：ロボ）
- 本文は実用的・具体的に、読者が今すぐ行動できる内容にする

出力形式：必ず有効なJSONのみを返す。マークダウンコードブロックは使わない。`

function buildUserPrompt(idea: ArticleIdea, relatedSlugs: string[]): string {
  return `以下の記事アイデアに基づいて、防災Lab向けの記事下書きをJSONで生成してください。

## 記事アイデア
- タイトル: ${idea.title}
- スラッグ: ${idea.slug}
- カテゴリ: ${idea.category}
- ターゲットキーワード: ${idea.targetKeyword}
- 読者の意図: ${idea.intent}
- 収益アイテム: ${(idea.monetizeItems ?? []).join('、')}

## 関連スラッグ候補（同カテゴリの既存記事）
${relatedSlugs.join(', ')}

## 出力するJSONの構造

{
  "frontmatter": {
    "title": "記事タイトル（40字以内）",
    "description": "meta description（80〜120字）",
    "emoji": "絵文字1文字",
    "conclusion": "結論1文（60字以内）",
    "reasons": [
      { "title": "理由タイトル", "body": "理由の説明（50字程度）", "emoji": "絵文字" },
      { "title": "理由タイトル", "body": "理由の説明（50字程度）", "emoji": "絵文字" },
      { "title": "理由タイトル", "body": "理由の説明（50字程度）", "emoji": "絵文字" }
    ],
    "manga": {
      "panels": [
        { "character": "riss", "emotion": "worried", "message": "疑問・不安（20字以内）" },
        { "character": "robot", "emotion": "serious", "message": "結論を一言（20字以内）" },
        { "character": "robot", "emotion": "normal", "message": "理由を一言（20字以内）" },
        { "character": "riss", "emotion": "relieved", "message": "次の行動（20字以内）" }
      ]
    },
    "faqs": [
      { "question": "よくある質問1", "answer": "回答1（80字程度）" },
      { "question": "よくある質問2", "answer": "回答2（80字程度）" },
      { "question": "よくある質問3", "answer": "回答3（80字程度）" }
    ],
    "relatedSlugs": ${JSON.stringify(relatedSlugs.slice(0, 3))},
    "monetizeItems": ${JSON.stringify(idea.monetizeItems ?? [])},
    "region": {
      "name": "武蔵野市",
      "content": "武蔵野市に関連した具体的な情報（100字程度）"
    },
    "mangaPrompt": "4コマ漫画のイラスト生成用プロンプト（英語・50語程度）"
  },
  "body": "## 結論\\n\\n（本文全体。以下の構成で記述）\\n1. 結論\\n2. 理由3つ\\n3. 詳しい解説\\n4. やってはいけないこと\\n5. 今すぐできる対策\\n6. 武蔵野市の場合\\n7. 必要な備え\\n8. FAQ（本文中に<FAQ>コンポーネントなし、frontmatterのfaqsで管理）\\n9. 関連記事への誘導"
}

bodyは500〜800字程度のMarkdown。## 見出しを使い、実用的な内容にしてください。`
}

// =====================================================
// MDX ファイル生成
// =====================================================

type GeneratedData = {
  frontmatter: Record<string, unknown>
  body: string
}

function buildMdxContent(idea: ArticleIdea, generated: GeneratedData): string {
  const fm = generated.frontmatter
  const today = new Date().toISOString().slice(0, 10)

  const data: Record<string, unknown> = {
    title: fm.title,
    description: fm.description,
    category: idea.category,
    date: today,
    emoji: fm.emoji,
    status: 'draft',
    reviewRequired: true,
    autoGenerated: true,
    conclusion: fm.conclusion,
    reasons: fm.reasons,
    manga: fm.manga,
    faqs: fm.faqs,
    relatedSlugs: fm.relatedSlugs,
    monetizeItems: fm.monetizeItems,
    region: fm.region,
    xSeries: idea.xSeries,
    mangaPrompt: fm.mangaPrompt,
  }

  return matter.stringify(generated.body ?? '', data)
}

// =====================================================
// メイン
// =====================================================

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const force = args.includes('--force')
  const slugIndex = args.indexOf('--slug')
  const targetSlug = slugIndex >= 0 ? args[slugIndex + 1] : null
  const limitIndex = args.indexOf('--limit')
  const limit = limitIndex >= 0 ? parseInt(args[limitIndex + 1], 10) : Infinity

  const client = initClient()

  const ideas: ArticleIdea[] = JSON.parse(fs.readFileSync(IDEAS_PATH, 'utf-8'))
  const existingDrafts = new Set(getAllDraftSlugs())
  const publishedSlugs = new Set(getAllSlugs())

  if (!fs.existsSync(DRAFTS_DIR)) fs.mkdirSync(DRAFTS_DIR, { recursive: true })

  const targets = ideas.filter((idea) => {
    if (targetSlug && idea.slug !== targetSlug) return false
    if (!force && publishedSlugs.has(idea.slug)) {
      console.log(`[skip] ${idea.slug} — 公開済み記事あり`)
      return false
    }
    if (!force && existingDrafts.has(idea.slug)) {
      console.log(`[skip] ${idea.slug} — 既存の下書きあり（--force で上書き可）`)
      return false
    }
    return true
  }).slice(0, limit)

  if (targets.length === 0) {
    console.log('生成対象がありません。')
    return
  }

  console.log(`\n生成対象: ${targets.length} 件\n`)

  for (const idea of targets) {
    console.log(`\n━━━ [${idea.slug}] 生成中 ━━━`)
    console.log(`タイトル: ${idea.title}`)

    const relatedSlugs = getSameCategoryRelated(idea.category, idea.slug)

    let generated: GeneratedData | null = null
    let attempt = 0

    while (attempt < 3 && !generated) {
      attempt++
      try {
        console.log(`  Claude API 呼び出し (attempt ${attempt})...`)
        const res = await client.messages.create({
          model: 'claude-sonnet-4-6',
          max_tokens: 4096,
          system: SYSTEM_PROMPT,
          messages: [{ role: 'user', content: buildUserPrompt(idea, relatedSlugs) }],
        })

        const text = res.content[0].type === 'text' ? res.content[0].text : ''
        const cleaned = text.replace(/^```json\s*/i, '').replace(/\s*```$/, '').trim()
        generated = JSON.parse(cleaned) as GeneratedData
        console.log(`  JSON パース成功`)
      } catch (e) {
        console.warn(`  attempt ${attempt} 失敗:`, e instanceof Error ? e.message : e)
        if (attempt >= 3) throw e
      }
    }

    if (!generated) throw new Error(`${idea.slug} の生成に失敗しました`)

    const mdxContent = buildMdxContent(idea, generated)
    const outPath = path.join(DRAFTS_DIR, `${idea.slug}.mdx`)
    fs.writeFileSync(outPath, mdxContent, 'utf-8')
    console.log(`  保存: content/drafts/${idea.slug}.mdx`)
  }

  console.log('\n✅ 生成完了\n')
}

main().catch((err) => {
  console.error('❌ エラー:', err)
  process.exit(1)
})
