/**
 * 下書き公開スクリプト
 *
 * content/drafts/<slug>.mdx をレビュー済みとして content/articles/ へ移動する。
 * - status / reviewRequired を除去（autoGenerated は履歴として残す）
 * - date を公開日（今日）に更新
 * - 漫画画像（public/manga/<slug>/comic.png）が無い場合は警告
 *
 * 実行例:
 *   npx tsx scripts/publishDraft.ts --slug blackout-smartphone-battery
 *   npx tsx scripts/publishDraft.ts --slug xxx --keep-date   # dateを更新しない
 */

import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'

const DRAFTS_DIR = path.join(process.cwd(), 'content', 'drafts')
const ARTICLES_DIR = path.join(process.cwd(), 'content', 'articles')
const MANGA_DIR = path.join(process.cwd(), 'public', 'manga')

function main(): void {
  const args = process.argv.slice(2)
  const slugIndex = args.indexOf('--slug')
  const slug = slugIndex >= 0 ? args[slugIndex + 1] : null
  const keepDate = args.includes('--keep-date')

  if (!slug) {
    console.error('使い方: npx tsx scripts/publishDraft.ts --slug <slug>')
    process.exit(1)
  }

  const draftPath = path.join(DRAFTS_DIR, `${slug}.mdx`)
  const articlePath = path.join(ARTICLES_DIR, `${slug}.mdx`)

  if (!fs.existsSync(draftPath)) {
    console.error(`❌ 下書きが見つかりません: content/drafts/${slug}.mdx`)
    process.exit(1)
  }
  if (fs.existsSync(articlePath)) {
    console.error(`❌ 同名の公開記事が既に存在します: content/articles/${slug}.mdx`)
    process.exit(1)
  }

  const raw = fs.readFileSync(draftPath, 'utf-8')
  const { data, content } = matter(raw)

  delete data.status
  delete data.reviewRequired
  if (!keepDate) data.date = new Date().toISOString().slice(0, 10)

  fs.writeFileSync(articlePath, matter.stringify(content, data), 'utf-8')
  fs.unlinkSync(draftPath)

  console.log(`✅ 公開しました: content/articles/${slug}.mdx`)

  if (!fs.existsSync(path.join(MANGA_DIR, slug, 'comic.png'))) {
    console.warn(`⚠️ 漫画画像がありません。生成してください:`)
    console.warn(`   node scripts/generate-article-manga.js --slug ${slug}`)
  }
  console.log('変更を commit / push すると Vercel にデプロイされます。')
}

main()
